;title='BootSound'
;version=1.0.0
;creator=CROX
;about='BootSound MP3 configurator for Nintendo Switch.'
;color=cyan

[BootSound]
[*Open BootSound]
launch /switch/V2.01.nro

[About]
[*About BootSound]
notify-now 'BootSound | CROX'
