;title='Dil Koprusu'
;version=0.1.0
;creator=CROX
;about='Switch oyunlari icin Turkce yama, altyazi ve dublaj yoneticisi.'
;color=cyan

[SwitchTurkceOverlay]
[*Open SwitchTurkce Overlay]
launch /switch/SwitchTurkceOverlay.nro

[About]
[*About SwitchTurkce Overlay]
notify-now 'Switch Turkce Overlay | CROX'