name: Build Switch BootSound

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    container: devkitpro/devkitaarch64:latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Build App
        run: |
          make

      - name: Upload NRO Output
        uses: actions/upload-artifact@v3
        with:
          name: BootSound-NRO
          path: BootSound.nro

      - name: Upload NSP Output
        uses: actions/upload-artifact@v3
        with:
          name: BootSound-NSP
          path: BootSound.nsp